- name: Configure VM for DevOps Project
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT package cache (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - unzip
        - # Add other necessary packages here

    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present
      when: ansible_os_family == "Debian"

    - name: Install MongoDB (if needed)
      apt:
        name: mongodb
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Java is installed
      become: yes
      apt:
        name: openjdk-11-jdk  # Install OpenJDK 11
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins APT repository key
      become: yes
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
      when: ansible_os_family == "Debian"

    - name: Add Jenkins APT repository
      become: yes
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Jenkins
      become: yes
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Enable and start Jenkins service
      become: yes
      systemd:
        name: jenkins
        enabled: yes
        state: started
      when: ansible_os_family == "Debian"

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: ansible_os_family == 'Debian'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Update apt package cache (again)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'
